mysql:
  enabled: false
  host: "localhost"
  port: 3306
  database: "treexbuyer"
  username: "root"
  password: ""

debug: false

priceItem:
  path: priceItem.yml

menu:
  seller:
    path: Menu/seller.yml
  mobs:
    path: Menu/mobs.yml
  mine:
    path: Menu/mine.yml

autobuy:
  delay: 60  # In ticks. How often AutoBuy will be triggered. Default is 60 - 3 seconds
  actions:
    - '[MESSAGE] &8&l> &fAutomatically sold items worth &a&l%sell_pay%&f, and &c&l%sell_score% &fpoints.'
  disabled-worlds:
    - duel-1
    - duel-2
  status:
    enable: "&aEnabled"
    disable: "&cDisabled"

messages:
  sell: "&8&l> &fYou have successfully sold items worth &a&l%sell_pay%&f, and &c&l%sell_score% &fpoints."
  noItems: "&cYou have no items to sell."

# for every 100 points the player will receive +0.1 to the coefficient
score-to-multiplier-ratio:
  scores: 100
  coefficient: 0.01

# maximum coefficient (excluding donation boosts)
max-legal-coefficient: 3
default-coefficient: 1
# if true, donation boosts will bypass the value in max-legal-coefficient
boosters_except_legal_coefficient: true
booster:
  donat-1: # name (can be any)
    permission: 'buyer.boost.donat1' # (permission by which the presence of a boost will be determined)
    external-coefficient: 0.5

